### ISSUE TITLE
Footer - should show version number

### ISSUE THREAD

**Issue by wicksipedia** [SSWConsulting/SSW.CodeAuditor#121]
cc @adamcogan @nvhoanganh 

Was trying to work out why some changes I pushed weren't working as expected in CodeAuditor. Couldn't work out if my changes were actually pushed to production since it is missing version information in the footer (I think there is a rule on this)

![image](https://user-images.githubusercontent.com/600044/103384970-88398200-4b4c-11eb-82ec-34408e1795aa.png)

It would be good to see when the latest build was deployed and what was changed in it (e.g. release notes) like our other products

![image](https://user-images.githubusercontent.com/600044/103384954-7061fe00-4b4c-11eb-8b3b-6eb8461b8ad9.png)

1. Ensure footer is visible on all pages
2. In footer, show when latest build was deployed
3. In footer, show build number with link to more information in GitHub

**Comment by tombui99** [comment]
Hi @wicksipedia 

Done - Footer with build datetime has been added

![image](https://user-images.githubusercontent.com/67776356/110578329-a8bf3180-81b8-11eb-9f2b-2037d4fec821.png)
**Figure: New footer on CodeAuditor**

**Comment by nvhoanganh** [comment]
Hi Tom,

The footer need to stick to the bottom of the page,

[image: image.png]

also, what is the HTML link and the "Find us on" ?


Thanks and Regards,

Anthony Nguyen
0413 725 625

**Comment by tombui99** [comment]
Hi @nvhoanganh 

Done - Footer fixed (footer sticks to bottom of the page, HTML link removed, change to Find us on Facebook)

<img width="1432" alt="Screen Shot 2021-03-11 at 12 24 39 pm" src="https://user-images.githubusercontent.com/67776356/110721685-1cb71380-8265-11eb-8eba-44abc8c127d7.png">

**Comment by nvhoanganh** [comment]
are you sure?

it is still not working for me

[image: image.png]
Thanks and Regards,

Anthony Nguyen
0413 725 625

**Comment by bfabiny** [comment]
Estimate: 1
Blocked By Issue: https://github.com/SSWConsulting/SSW.CodeAuditor/issues/148
