### ISSUE TITLE
🐛 Bug - Working link is being reported as broken

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.CodeAuditor#369]
Hi @tombui99  

### Describe the Bug

On this report https://codeauditor.com/build/04136f0a-2f5d-44b6-8f5f-7f8c307edf6e

The 1 reported 404 is not actually broken:
Page: https://www.ssw.com.au/rules/rules-to-better-research-and-development
Link: https://www.ato.gov.au/Business/Research-and-development-tax-incentive/ 

<img width="1353" alt="Screen Shot 2022-09-07 at 3 14 02 PM" src="https://user-images.githubusercontent.com/12601228/188993098-709c7157-2359-4e3a-8a11-155604a61347.png">

### To Reproduce

1. Go to https://www.ssw.com.au/rules/rules-to-better-research-and-development
2. Click on link https://www.ato.gov.au/Business/Research-and-development-tax-incentive/  and see the page is up and running

### Tasks

- [ ] Investigate
- [ ] Fix

Thanks!

**Comment by tiagov8** [comment]
Hi @tombui99 

FYI - same is happening for this link: https://learn.microsoft.com/en-us/assessments/azure-architecture-review/ 
on this rule: https://ssw.com.au/rules/well-architected-framework

<img width="1216" alt="Screen Shot 2022-12-19 at 4 02 21 PM" src="https://user-images.githubusercontent.com/12601228/208551253-af35f577-ff59-472a-b32d-b9ead27b4d41.png">

Related: #397

**Comment by tombui99** [comment]
Hi Tiago, 

> Fix working links reported as broken

Done - above links no longer reported as broken

**Comment by tiagov8** [comment]
Hey @tombui99 

(reopening Issue)

This working link is still showing as broken in the latest report:
https://learn.microsoft.com/en-us/assessments/azure-architecture-review/

Also it would be great if we have some information on what caused the issue, and how it has been fixed

<img width="1374" alt="Screenshot 2023-04-04 at 12 29 31 PM" src="https://user-images.githubusercontent.com/12601228/229842618-fad84018-ea76-407b-a025-a2686ec68bf0.png">

[ ] Investigate and fix
[ ] Add details on your done so we can avoid/fix in easier in the future

Cheers,

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan @william-liebenberg 

As per our conversation, I have had this discussion with Anthony previously, we confirmed that some sites like Microsoft or Twitter has some sort of anti web scraping mechanism that it either has login authentication or returns a bunch of cors network errors (as screenshot below). Hence, this makes CodeAuditor reports the website as an error even though it is still working. 

Our solution is to simply ignore these sites.

![image](https://user-images.githubusercontent.com/67776356/232646012-bd69b98a-fd41-4eed-82a5-c5dcf1a5df34.png)

**Figure: Microsoft websites returning several cors network errors**

**Comment by adamcogan** [comment]
Hi @tombui99 
CC @william-liebenberg 

1. Read https://ssw.com.au/rules/do-you-have-a-knowledge-base-kb/
2. Implement by using the GitHub Wiki for the KB
3. Put that screenshot from CodeAuditor wiki on that rule + a link to it as an example

-a
www.adamcogan.com.au

**Comment by tombui99** [comment]
Hi @adamcogan 
cc @william-liebenberg 

I have created a new GitHub issue for the Wiki
See https://github.com/SSWConsulting/SSW.CodeAuditor/issues/429
