### ISSUE TITLE
✨ Schedule SSW Rules scan every 2 weeks

### ISSUE THREAD

**Issue by tombui99** [SSWConsulting/SSW.CodeAuditor#412]
Cc: @adamcogan 

Hi @tiagov8 
 
### Pain 
As per our conversation, we would want to schedule a CodeAuditor scan on SSW Rules every 2 weeks

### Suggested Solution
Set up a new Github action and schedule it to scan SSW Rules every 2 weeks

### Tasks

- [x] Schedule an automated Github action that scan SSW Rules every 2 weeks

Thanks!

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

> Schedule an automated Github action that scan SSW Rules every 2 weeks

Done - I have added a scheduled Github action that triggers a scan on the 1st and 14th of every month

See https://github.com/SSWConsulting/SSW.CodeAuditor/blob/sswrules-scan-config/.github/workflows/main.yml

**Comment by tiagov8** [comment]
Hi @tombui99 

1. I thought this was 'done' but the Issue is still "Open". Any reason?

2. When I look at https://codeauditor.com/explore I expected to see the previous SSW.Rules scan from **2 weeks** ago, so I could compare with the latest one...   
     ....but it's not there... 
     
     Please fix
     
    <img width="1338" alt="Screenshot 2023-03-15 at 5 05 03 PM" src="https://user-images.githubusercontent.com/12601228/225430286-44b59557-0982-4146-b23d-184e1e53fa0c.png">

3. What does the column "Total build: X" mean?

**Comment by tombui99** [comment]
Hi @tiagov8 

As per our conversation, in order to see all the scan for SSW Rules, you need to click the down arrow on the far right to expand the list 

![image](https://user-images.githubusercontent.com/67776356/225460984-fb806e12-a35e-46cb-92f2-56b6e5ce5f0e.png)

**Figure: List of all scans for SSW Rules within the past 2 weeks**

> What does the column "Total build: X" mean?

"Total build" means the total number of scans that have been ran on the corresponding URL

**Comment by tiagov8** [comment]
Hi @tombui99 

That is not intuitive...

1. Please change from

> Total build: X

to

> Scan history: X

---

Also, I am not sure why we have a "Showing top 1000 Public Scans" link... link does nothing and top 1000 is definitely not necessary

2. Please change from
> Explore SSW CodeAuditor
> Showing top 1000 Public Scans

to
> SSW CodeAuditor Latest Public Scans

---

3. Is there a way we can merge links with "www" with the same links without it?

<img width="1153" alt="Screenshot 2023-03-16 at 10 36 26 AM" src="https://user-images.githubusercontent.com/12601228/225634133-b814d9c8-ee58-4dc0-b482-1f0edb02f05a.png">

---

4. What does 143 mean here? I don't relate this number with anything in the latest scan...
<img width="984" alt="Screenshot 2023-03-16 at 10 39 46 AM" src="https://user-images.githubusercontent.com/12601228/225634984-ae7839bb-84bd-4908-8fb7-a78b03276fd5.png">

**Comment by tombui99** [comment]
Hi @tiagov8 
CC @adamcogan 

Closing this issue as the task for scheduling Scan on SSW Rules have been done.

I have created 2 new issues as per Tiago's comments
See https://github.com/SSWConsulting/SSW.CodeAuditor/issues/418
